CREATE TABLE IF NOT EXISTS "Method" (
  "id" SERIAL PRIMARY KEY,
  "name" TEXT NOT NULL UNIQUE,
  "durationValue" INTEGER NOT NULL,
  "durationUnit" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "Unit" (
  "id" TEXT PRIMARY KEY,
  "name" TEXT NOT NULL UNIQUE,
  "email" TEXT NOT NULL,
  "phone" TEXT NOT NULL,
  "managerName" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO "Method" ("name", "durationValue", "durationUnit") VALUES
('QUENTE', 3, 'hours'),
('PISTA FRIA', 3, 'hours'),
('DESCONGELANDO', 3, 'days'),
('RESFRIADO', 3, 'days'),
('CONGELADO', 30, 'days'),
('AMBIENTE SECOS', 30, 'days')
ON CONFLICT ("name") DO NOTHING;
